services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypw
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 5s

  web:
    build: .
    command: sh -c "uv run manage.py migrate && uv run manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy


