openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /recordsjson:
    post:
      operationId: recordsjson_create
      tags:
      - recordsjson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordsJson'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RecordsJson'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RecordsJson'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
        '409':
          description: No response body
        '400':
          description: No response body
components:
  schemas:
    RecordsJson:
      type: object
      properties:
        request_id:
          type: integer
        user_id:
          type: integer
        word_count:
          type: integer
        timestamp:
          type: string
          format: date-time
      required:
      - request_id
      - user_id
      - word_count
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
