openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /recordsjson:
    post:
      operationId: recordsjson_create
      description: Record learning activity
      tags:
      - recordsjson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordsJson'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RecordsJson'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RecordsJson'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
        '409':
          description: No response body
        '400':
          description: No response body
  /users/{user_id}/summary:
    get:
      operationId: users_summary_list
      description: Simple moving average of words learned by a user for specific range
        and granularity
      parameters:
      - in: query
        name: from
        schema:
          type: string
          format: date-time
        required: true
      - in: query
        name: granularity
        schema:
          enum:
          - hour
          - day
          - month
          type: string
          minLength: 1
        description: |-
          * `hour` - hour
          * `day` - day
          * `month` - month
        required: true
      - in: query
        name: to
        schema:
          type: string
          format: date-time
        required: true
      - in: path
        name: user_id
        schema:
          type: string
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSummaryResponse'
          description: ''
components:
  schemas:
    GranularityEnum:
      enum:
      - hour
      - day
      - month
      type: string
      description: |-
        * `hour` - hour
        * `day` - day
        * `month` - month
    RecordsJson:
      type: object
      properties:
        request_id:
          type: string
          format: uuid
        user_id:
          type: string
        word_count:
          type: integer
          minimum: 0
        timestamp:
          type: string
          format: date-time
      required:
      - request_id
      - user_id
      - word_count
    UserSummaryResponse:
      type: object
      properties:
        period:
          type: string
          format: date-time
        granularity:
          $ref: '#/components/schemas/GranularityEnum'
      required:
      - granularity
      - period
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
